<?php

$form->get('nome')->setAttributes([
	'class' => 'form-control',
	'placeholder' => 'Nome utente'
]);

$form->get('cognome')->setAttributes([
	'class' => 'form-control',
	'placeholder' => 'Cognome utente'
]);

$form->get('email')->setAttributes([
	'class' => 'form-control',
	'placeholder' => 'name@yourcompany.com'
]);


$form->get('password')->setAttributes([
	'class' => 'form-control',
	'placeholder' => 'Minimo 6 caratteri'
]);

$form->get('conferma_password')->setAttributes([
	'class' => 'form-control',
	'placeholder' => 'Ripeti la password'
]);

$form->get('registra')->setAttributes(array('class' => 'btn btn-primary'));
$form->get('cancella')->setAttributes(array('class' => 'btn btn-default'));

$form->prepare();
?>

<h1>Registrazione Utente</h1>

<div class="row">
	<div class="col-md-6">
		<?= $this->form()->openTag($form); ?>

		<div class="form-group">
			<?= $this->formLabel($form->get('nome')); ?>
			<?= $this->formElement($form->get('nome')); ?>
			<?= $this->formElementErrors($form->get('nome')); ?>
		</div>

		<div class="form-group">
			<?= $this->formLabel($form->get('cognome')); ?>
			<?= $this->formElement($form->get('cognome')); ?>
			<?= $this->formElementErrors($form->get('cognome')); ?>
		</div>

		<div class="form-group">
			<?= $this->formLabel($form->get('email')); ?>
			<?= $this->formElement($form->get('email')); ?>
			<?= $this->formElementErrors($form->get('email')); ?>
		</div>


		<div class="form-group">
			<?= $this->formLabel($form->get('password')); ?>
			<?= $this->formElement($form->get('password')); ?>
			<?= $this->formElementErrors($form->get('password')); ?>
		</div>

		<div class="form-group">
			<?= $this->formLabel($form->get('conferma_password')); ?>
			<?= $this->formElement($form->get('conferma_password')); ?>
			<?= $this->formElementErrors($form->get('conferma_password')); ?>
		</div>

		<div class="form-group">
			<?= $this->formElement($form->get('registra')); ?>
			<?= $this->formElement($form->get('cancella')); ?>
		</div>

		<?= $this->formElement($form->get('csrf')); ?>

		<?= $this->form()->closeTag(); ?>
	</div>
</div>