<?php
$form->get('email')->setAttributes([
	'class' => 'form-control',
	'placeholder' => 'name@yourcompany.com'
]);

$form->get('password')->setAttributes([
	'class' => 'form-control',
	'placeholder' => 'Minimo 6 caratteri'
]);

$form->get('accedi')->setAttributes(array('class' => 'btn btn-primary'));

$form->prepare();
?>

<h1>Login</h1>

<?php if ($this->message) : ?><p><b><?= $this->message; ?></b></p><?php endif; ?>
<div class="row">
	<div class="col-md-6">
		<?= $this->form()->openTag($form); ?>

		<div class="form-group">
			<?= $this->formLabel($form->get('email')); ?>
			<?= $this->formElement($form->get('email')); ?>
			<?= $this->formElementErrors($form->get('email')); ?>
		</div>

		<div class="form-group">
			<?= $this->formLabel($form->get('password')); ?>
			<?= $this->formElement($form->get('password')); ?>
			<?= $this->formElementErrors($form->get('password')); ?>
		</div>

		<div class="form-group">
			<?= $this->formElement($form->get('accedi')); ?>
		</div>

		<?= $this->formElement($form->get('csrf')); ?>

		<?= $this->form()->closeTag(); ?>
	</div>
</div>