<h1>Profilo utente</h1>

<div class="row">
    <div class="col-md-12">
        <div class="col-md-3"><b>Nome</b></div>
        <div class="col-md-9"><?= $this->utente->getNome(); ?></div>
    </div>
    <div class="col-md-12">
        <div class="col-md-3"><b>Cognome</b></div>
        <div class="col-md-9"><?= $this->utente->getCognome(); ?></div>
    </div>
    <div class="col-md-12">
        <div class="col-md-3"><b>Email</b></div>
        <div class="col-md-9"><?= $this->utente->getEmail(); ?></div>
    </div>
</div>